shfSecurity:
  index:
    security: false
  logoin:
    security: false
  logout:
    security: true
  noPermission:
    security: false
  exception:
    security: false

default:
  index:
    security: true
    credentials:
      - [admin, invitado]
      
config:
  index:
    security: false
  create:
    security: false

usuario:
  index:
    security: true
    credentials:
      - [admin, invitado]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
      
dataUser:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
      
      
      
      
insumo:
  index:
    security: true
    credentials:
      - [admin, invitado]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
      
      
animal:
  indexAnimal:
    security: true
    credentials:
      - [admin, invitado]
  insertAnimal:
    security: true
    credentials:
      - [admin]
  createAnimal:
    security: true
    credentials:
      - [admin]
  editAnimal:
    security: true
    credentials:
      - [admin]
  updateAnimal:
    security: true
    credentials:
      - [admin]
  deleteAnimal:
    security: true
    credentials:
      - [admin]
  deleteSelectAnimal:
    security: true
    credentials:
      - [admin]
  indexRaza:
    security: true
    credentials:
      - [admin, invitado]
  insertRaza:
    security: true
    credentials:
      - [admin]
  createRaza:
    security: true
    credentials:
      - [admin]
  editRaza:
    security: true
    credentials:
      - [admin]
  updateRaza:
    security: true
    credentials:
      - [admin]
  deleteRaza:
    security: true
    credentials:
      - [admin]
  deleteSelectRaza:
    security: true
    credentials:
      - [admin]
  indexLote:
    security: true
    credentials:
      - [admin, invitado]
  insertLote:
    security: true
    credentials:
      - [admin]
  createLote:
    security: true
    credentials:
      - [admin]
  editLote:
    security: true
    credentials:
      - [admin]
  updateLote:
    security: true
    credentials:
      - [admin]
  deleteLote:
    security: true
    credentials:
      - [admin]
  deleteSelectLote:
    security: true
    credentials:
      - [admin]
      
