shfSecurity:
  index:
    security: false
  login:
    security: false
  logout:
    security: true
  noPermission:
    security: false
  exception:
    security: false

default:
  index:
    security: true
    credentials:
      - [admin, invitado]
      
recuperar:
  index:
    security: true
    credentials:
      - [admin]
  consultar:
    security: true
    credentials:
      - [admin]
  recuperar:
    security: true
    credentials:
      - [admin]
config:
  index:
    security: false
  create:
    security: false
  
usuario:
  indexUsuario:
    security: true
    credentials:
      - [admin, invitado]
  insertDatos:
    security: true
    credentials:
      - [admin]
  insertUsuario:
    security: true
    credentials:
      - [admin]
  createUsuario:
    security: true
    credentials:
      - [admin]
  editUsuario:
    security: true
    credentials:
      - [admin]
  updateUsuario:
    security: true
    credentials:
      - [admin]
  deleteUsuario:
    security: true
    credentials:
      - [admin]
  deleteSelectUsuario:
    security: true
    credentials:
      - [admin]
  viewUsuario:
    security: true
    credentials:
      - [admin, invitado]
  reportUsuario:
    security: true
    credentials:
      - [admin, invitado]
  deleteFiltersUsuario:
    security: true
    credentials:
      - [admin, invitado]
      
dataUser:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
      
credencial:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
      
usuarioCredencial:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  delectSelect:
    security: true
    credentials:
      - [admin]
      
insumo:
  index:
    security: true
    credentials:
      - [admin, invitado]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
      
      
animal:
  indexAnimal:
    security: true
    credentials:
      - [admin, invitado]
  insertAnimal:
    security: true
    credentials:
      - [admin]
  createAnimal:
    security: true
    credentials:
      - [admin]
  editAnimal:
    security: true
    credentials:
      - [admin]
  updateAnimal:
    security: true
    credentials:
      - [admin]
  deleteAnimal:
    security: true
    credentials:
      - [admin]
  deleteSelectAnimal:
    security: true
    credentials:
      - [admin]
  indexRaza:
    security: true
    credentials:
      - [admin, invitado]
  insertRaza:
    security: true
    credentials:
      - [admin]
  createRaza:
    security: true
    credentials:
      - [admin]
  editRaza:
    security: true
    credentials:
      - [admin]
  updateRaza:
    security: true
    credentials:
      - [admin]
  deleteRaza:
    security: true
    credentials:
      - [admin]
  deleteSelectRaza:
    security: true
    credentials:
      - [admin]
  indexLote:
    security: true
    credentials:
      - [admin, invitado]
  insertLote:
    security: true
    credentials:
      - [admin]
  createLote:
    security: true
    credentials:
      - [admin]
  editLote:
    security: true
    credentials:
      - [admin]
  updateLote:
    security: true
    credentials:
      - [admin]
  deleteLote:
    security: true
    credentials:
      - [admin]
  deleteSelectLote:
    security: true
    credentials:
      - [admin]
      
personal:
  indexEmpleado:
    security: true
    credentials:
      - [admin, invitado]
  insertEmpleado:
    security: true
    credentials:
      - [admin]
  createEmpleado:
    security: true
    credentials:
      - [admin]
  editEmpleado:
    security: true
    credentials:
      - [admin]
  updateEmpleado:
    security: true
    credentials:
      - [admin]
  deleteEmpleado:
    security: true
    credentials:
      - [admin]
  deleteSelectEmpleado:
    security: true
    credentials:
      - [admin]
  indexCliente:
    security: true
    credentials:
      - [admin, invitado]
  insertCliente:
    security: true
    credentials:
      - [admin]
  createCliente:
    security: true
    credentials:
      - [admin]
  editCliente:
    security: true
    credentials:
      - [admin]
  updateCliente:
    security: true
    credentials:
      - [admin]     
  indexVeterinario:
    security: true
    credentials:
      - [admin, invitado]
  insertVeterinario:
    security: true
    credentials:
      - [admin]
  createVeterinario:
    security: true
    credentials:
      - [admin]
  editVeterinario:
    security: true
    credentials:
      - [admin]
  updateVeterinario:
    security: true
    credentials:
      - [admin]

      
vacunacion:
  indexVacunacion:
    security: true
    credentials:
      - [admin, invitado]
  insertVacunacion:
    security: true
    credentials:
      - [admin]
  createVacunacion:
    security: true
    credentials:
      - [admin]
  editVacunacion:
    security: true
    credentials:
      - [admin]
  updateVacunacion:
    security: true
    credentials:
      - [admin]
  deleteVacunacion:
    security: true
    credentials:
      - [admin]
  deleteSelectVacunacion:
    security: true
    credentials:
      - [admin]
  reporteVacunacion:
    security: true
    credentials:
      - [admin]
  deleteFiltersVacunacion:
    security: true
    credentials:
      - [admin]
  traductorVacunacion:
    security: true
    credentials:
      - [admin]
  viewVacunacion:
    security: true
    credentials:
      - [admin, invitado]
  deleteSelectDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  deleteFiltersDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  reporteDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  traductorDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  indexDetalleVacunacion:
    security: true
    credentials:
      - [admin, invitado]
  insertDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  createDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  editDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  updateDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  deleteDetalleVacunacion:
    security: true
    credentials:
      - [admin]  
  indexVacuna:
    security: true
    credentials:
      - [admin, invitado]
  insertVacuna:
    security: true
    credentials:
      - [admin]
  createVacuna:
    security: true
    credentials:
      - [admin]
  editVacuna:
    security: true
    credentials:
      - [admin]
  updateVacuna:
    security: true
    credentials:
      - [admin]
  deleteVacuna:
    security: true
    credentials:
      - [admin]
  deleteSelectVacuna:
    security: true
    credentials:
      - [admin]
  deleteSelectDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  deleteFiltersDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  reporteDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  traductorDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  indexDetalleVacunacion:
    security: true
    credentials:
      - [admin, invitado]
  insertDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  createDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  editDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  updateDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  deleteDetalleVacunacion:
    security: true
    credentials:
      - [admin]  
  indexVacuna:
    security: true
    credentials:
      - [admin, invitado]
  insertVacuna:
    security: true
    credentials:
      - [admin]
  createVacuna:
    security: true
    credentials:
      - [admin]
  editVacuna:
    security: true
    credentials:
      - [admin]
  updateVacuna:
    security: true
    credentials:
      - [admin]
  deleteVacuna:
    security: true
    credentials:
      - [admin]
  deleteSelectVacuna:
    security: true
    credentials:
      - [admin]

      
factura:
  indexFacturaCompra:
    security: true
    credentials:
      - [admin, invitado]
  insertFacturaCompra:
    security: true
    credentials:
      - [admin]
  createFacturaCompra:
    security: true
    credentials:
      - [admin]
  editFacturaCompra:
    security: true
    credentials:
      - [admin]
  updateFacturaCompra:
    security: true
    credentials:
      - [admin]
  deleteFacturaCompra:
    security: true
    credentials:
      - [admin]
  deleteSelectFacturaCompra:
    security: true
    credentials:
      - [admin]
  reporteFacturaCompra:
    security: true
    credentials:
      - [admin]
  deleteFiltersFacturaCompra:
    security: true
    credentials:
      - [admin]
  traductorFacturaCompra:
    security: true
    credentials:
      - [admin]
  viewFacturaCompra:
    security: true
    credentials:
      - [admin]
  indexFacturaVenta:
    security: true
    credentials:
      - [admin, invitado]
  insertFacturaVenta:
    security: true
    credentials:
      - [admin]
  createFacturaVenta:
    security: true
    credentials:
      - [admin]
  editFacturaVenta:
    security: true
    credentials:
      - [admin]
  updateFacturaVenta:
    security: true
    credentials:
      - [admin]
  deleteFacturaVenta:
    security: true
    credentials:
      - [admin]
  deleteSelectFacturaVenta:
    security: true
    credentials:
      - [admin]
  reporteFacturaVenta:
    security: true
    credentials:
      - [admin]
  deleteFiltersFacturaVenta:
    security: true
    credentials:
      - [admin]
  traductorFacturaVenta:
    security: true
    credentials:
      - [admin]
  viewFacturaVenta:
    security: true
    credentials:
      - [admin]
      
      
      
