shfSecurity:
  index:
    security: false
  logoin:
    security: false
  logout:
    security: true
  noPermission:
    security: false
  exception:
    security: false

default:
  index:
    security: true
    credentials:
      - [admin, invitado]
      
config:
  index:
    security: false
  create:
    security: false

usuario:
  index:
    security: true
    credentials:
      - [admin, invitado]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
      
dataUser:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
      
      
      
      
insumo:
  index:
    security: true
    credentials:
      - [admin, invitado]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
      
      
animal:
  indexAnimal:
    security: true
    credentials:
      - [admin, invitado]
  insertAnimal:
    security: true
    credentials:
      - [admin]
  createAnimal:
    security: true
    credentials:
      - [admin]
  editAnimal:
    security: true
    credentials:
      - [admin]
  updateAnimal:
    security: true
    credentials:
      - [admin]
  deleteAnimal:
    security: true
    credentials:
      - [admin]
  deleteSelectAnimal:
    security: true
    credentials:
      - [admin]
  indexRaza:
    security: true
    credentials:
      - [admin, invitado]
  insertRaza:
    security: true
    credentials:
      - [admin]
  createRaza:
    security: true
    credentials:
      - [admin]
  editRaza:
    security: true
    credentials:
      - [admin]
  updateRaza:
    security: true
    credentials:
      - [admin]
  deleteRaza:
    security: true
    credentials:
      - [admin]
  deleteSelectRaza:
    security: true
    credentials:
      - [admin]
  indexLote:
    security: true
    credentials:
      - [admin, invitado]
  insertLote:
    security: true
    credentials:
      - [admin]
  createLote:
    security: true
    credentials:
      - [admin]
  editLote:
    security: true
    credentials:
      - [admin]
  updateLote:
    security: true
    credentials:
      - [admin]
  deleteLote:
    security: true
    credentials:
      - [admin]
  deleteSelectLote:
    security: true
    credentials:
      - [admin]
      
empleado:
  indexEmpleado:
    security: true
    credentials:
      - [admin, invitado]
  insertEmpleado:
    security: true
    credentials:
      - [admin]
  createEmpleado:
    security: true
    credentials:
      - [admin]
  editEmpleado:
    security: true
    credentials:
      - [admin]
  updateEmpleado:
    security: true
    credentials:
      - [admin]
  deleteEmpleado:
    security: true
    credentials:
      - [admin]
  deleteSelectEmpleado:
    security: true
    credentials:
      - [admin]
      
vacunacion:
  indexVacunacion:
    security: true
    credentials:
      - [admin, invitado]
  insertVacunacion:
    security: true
    credentials:
      - [admin]
  createVacunacion:
    security: true
    credentials:
      - [admin]
  editVacunacion:
    security: true
    credentials:
      - [admin]
  updateVacunacion:
    security: true
    credentials:
      - [admin]
  deleteVacunacion:
    security: true
    credentials:
      - [admin]
  deleteSelectVacunacion:
    security: true
    credentials:
      - [admin]
  reporteVacunacion:
    security: true
    credentials:
      - [admin]
  deleteFiltersVacunacion:
    security: true
    credentials:
      - [admin]
  traductorVacunacion:
    security: true
    credentials:
      - [admin]
  viewVacunacion:
    security: true
    credentials:
      - [admin]
  deleteSelectDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  deleteFiltersDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  reporteDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  traductorDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  indexDetalleVacunacion:
    security: true
    credentials:
      - [admin, invitado]
  insertDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  createDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  editDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  updateDetalleVacunacion:
    security: true
    credentials:
      - [admin]
  deleteDetalleVacunacion:
    security: true
    credentials:
      - [admin]  
  indexVacuna:
    security: true
    credentials:
      - [admin, invitado]
  insertVacuna:
    security: true
    credentials:
      - [admin]
  createVacuna:
    security: true
    credentials:
      - [admin]
  editVacuna:
    security: true
    credentials:
      - [admin]
  updateVacuna:
    security: true
    credentials:
      - [admin]
  deleteVacuna:
    security: true
    credentials:
      - [admin]
  deleteSelectVacuna:
    security: true
    credentials:
      - [admin]
      
      
      
