all:
  favicon: hola.ico
  title: Titulo de la pagina general

  meta:
    - charset="UTF-8"
  javascript:
    - jquery-1.11.1.min.js
    - index.js
    - bootstrap.js
  stylesheet:
    - bootstrap.css
    - main.css
    
shfSecurity:
  index:
    title: Identificacion del sistema
    stylesheet:
      - signin.css
      
ciudad:
  index:
    title: Ciudad
