all:
  favicon: favicon.ico
  title: Titulo de la pagina general

  meta:
    - charset="UTF-8"
  javascript:
    - jquery-1.11.1.min.js
    - index.js
    - bootstrap.js
    - main.js
  stylesheet:
    - bootstrap.css
    - font-awesome.css
    
shfSecurity:
  index:
    title: Identificacion del sistema
    stylesheet:
      - signin.css
      
usuario:
  index:
    title: Gestion de usuarios
    stylesheet:
      - main.css
  insert:
    title: Registro de un nuevo usuario
    stylesheet:
      - main.css
  edit:
    title: Modificar un usuario
    stylesheet:
      - main.css
default:
  index:
    stylesheet:
      - main.css
    javascript:
      - index.js

      
animal:
  indexAnimal:
    title: Gestion de cerdos
    stylesheet:
      - main.css
  insertAnimal:
    title: Registro de un nuevo cerdo
    stylesheet:
      - main.css
  editAnimal:
    title: Modificar un cerdo
    stylesheet:
      - main.css
      
  indexRaza:
    title: Gestion de raza
    stylesheet:
      - main.css
  insertRaza:
    title: Registro de una nueva raza
    stylesheet:
      - main.css
  editRaza:
    title: Modificar raza
    stylesheet:
      - main.css
      
  indexLote:
    title: Gestion de lotes
    stylesheet:
      - main.css
  insertLote:
    title: Registro de un nuevo lote
    stylesheet:
      - main.css
  editLote:
    title: Modificar un lote
    stylesheet:
      - main.css